#=============================================================================
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Copyright (c) 2022 minaminao
# License: GPLv3
#=============================================================================

[options]
# set spacevim theme. by default colorscheme layer is not loaded, if you want to use more colorscheme, please load the colorscheme layer
colorscheme = "gruvbox"
background = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit true colors
enable_guicolors = false
# Disable statusline separator, if you want to use other value, please install nerd fonts
statusline_separator = "nil"
statusline_inactive_separator = "bar"
buffer_index_type = 4
windows_index_type = 3
enable_tabline_filetype_icon = false
enable_statusline_display_mode = false
statusline_unicode_symbols = false
# Enable vim compatible mode, avoid changing origin vim key bindings
vimcompatible = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#rust"

[[custom_plugins]]
repo = 'mechatroner/rainbow_csv'
merged = false
